import { useEffect, useState } from "react";
import { Building2, Edit2, Eye, Plus, Power, Trash2 } from "lucide-react";
import toast from "react-hot-toast";
import Modal from "../components/Modal";
import { BranchPayload, createBranch, deleteBranch, getBranches, updateBranch } from "../features/branches/branches.api";
import { Link } from "react-router-dom";
import { useAuthStore } from "../store/auth.store";

const blank: BranchPayload = { name: "", branchCode: "", address: "", phone: "", email: "", status: "active" };
export default function BranchesPage() {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<any>(null); const [form, setForm] = useState<BranchPayload>(blank); const [open, setOpen] = useState(false);
  const { user } = useAuthStore(); const isSuperAdmin = user?.role === "superadmin";
  const load = async () => { setLoading(true); try { const res = await getBranches({ limit: 100 }); setItems(res.data?.data?.items || []); } catch { toast.error("Unable to load branches. Please try again."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { editing ? await updateBranch(editing._id, form) : await createBranch(form); toast.success(editing ? "Branch updated." : "Branch created."); setOpen(false); await load(); } catch (error: any) { toast.error(error.response?.data?.message || "Unable to save branch."); } };
  const toggle = async (branch: any) => { try { await updateBranch(branch._id, { status: branch.status === "active" ? "inactive" : "active" }); toast.success("Branch status updated."); load(); } catch { toast.error("Unable to update branch status."); } };
  const remove = async (branch: any) => { if (!window.confirm("Delete this branch? Branches with members or staff must be deactivated instead.")) return; try { await deleteBranch(branch._id); toast.success("Branch deleted."); load(); } catch (error: any) { toast.error(error.response?.data?.message || "Unable to delete branch."); } };
  return <div><div className="page-header flex-responsive"><div><h1>Branches</h1><p className="text-muted">Manage locations and branch operations.</p></div>{isSuperAdmin && <button className="btn btn-primary" onClick={() => { setEditing(null); setForm(blank); setOpen(true); }}><Plus size={17} /> Add branch</button>}</div>
    <div className="branch-grid">{loading ? <div className="glass-panel branch-empty">Loading branches...</div> : items.length ? items.map(branch => <article className="glass-panel branch-card" key={branch._id}><div className="branch-card-head"><div className="branch-mark"><Building2 size={20} /></div><span className={`status-badge ${branch.status}`}>{branch.status}</span></div><h2>{branch.name}</h2><p className="text-muted">{branch.branchCode}</p><p className="text-muted branch-address">{branch.address || "No address provided"}</p><div className="branch-card-actions"><Link className="btn btn-secondary" to={`/branches/${branch._id}`}><Eye size={16} /> View</Link><button className="btn-icon" title="Edit branch" onClick={() => { setEditing(branch); setForm({ name: branch.name, branchCode: branch.branchCode, address: branch.address || "", phone: branch.phone || "", email: branch.email || "", status: branch.status }); setOpen(true); }}><Edit2 size={16} /></button>{isSuperAdmin && <button className="btn-icon" title="Activate or deactivate" onClick={() => toggle(branch)}><Power size={16} /></button>}{isSuperAdmin && <button className="btn-icon danger" title="Delete branch" onClick={() => remove(branch)}><Trash2 size={16} /></button>}</div></article>) : <div className="glass-panel branch-empty">No branches available.</div>}</div>
    <Modal isOpen={open} onClose={() => setOpen(false)} title={editing ? "Edit branch" : "Add branch"}><form onSubmit={save}><div className="form-group"><label className="form-label">Branch name</label><input className="form-input" required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="form-group"><label className="form-label">Branch code</label><input className="form-input" required disabled={editing && !isSuperAdmin} value={form.branchCode} onChange={e => setForm({ ...form, branchCode: e.target.value.toUpperCase() })} /></div><div className="form-group"><label className="form-label">Address</label><textarea className="form-input" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /></div><div className="grid-cards" style={{ gridTemplateColumns: "1fr 1fr", gap: "1rem" }}><div className="form-group"><label className="form-label">Phone</label><input className="form-input" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></div><div className="form-group"><label className="form-label">Email</label><input className="form-input" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></div></div><button className="btn btn-primary" type="submit">{editing ? "Save changes" : "Create branch"}</button></form></Modal>
  </div>;
}