import { useEffect, useState } from "react";
import { ArrowLeft, CalendarCheck, CreditCard, IndianRupee, Users, UserSquare2 } from "lucide-react";
import toast from "react-hot-toast";
import { Link, useParams } from "react-router-dom";
import { getBranchOverview } from "../features/branches/branches.api";
import { getMembers } from "../features/members/members.api";
import { getTrainers } from "../features/trainers/trainers.api";
import { getAdminPayments } from "../features/payments/payments.api";

const money = (value: number) => `₹${(value || 0).toLocaleString("en-IN")}`;
export default function BranchDetailsPage() { const { id } = useParams(); const [data, setData] = useState<any>(null); const [members, setMembers] = useState<any[]>([]); const [staff, setStaff] = useState<any[]>([]); const [payments, setPayments] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!id) return; getBranchOverview(id).then(async overview => { const branchData = overview.data?.data; setData(branchData); const branchCode = branchData?.branch?.branchCode; const [memberRes, trainerRes, paymentRes] = await Promise.all([getMembers({ limit: 10, branchCode }), getTrainers({ branchCode }), getAdminPayments({ limit: 10, branchCode })]); setMembers(memberRes.data?.data?.items || []); setStaff(trainerRes.data?.data?.items || []); setPayments(paymentRes.data?.data?.items || []); }).catch(() => toast.error("Unable to load branch data. Please try again.")).finally(() => setLoading(false)); }, [id]);
  if (loading) return <div className="glass-panel branch-empty">Loading branch data...</div>; if (!data) return <div className="glass-panel branch-empty">Unable to load branch data.</div>; const { branch, kpis } = data;
  return <div><div className="page-header"><Link className="text-muted" to="/branches"><ArrowLeft size={16} /> Back to branches</Link><div className="flex-responsive" style={{ marginTop: ".75rem" }}><div><h1>{branch.name}</h1><p className="text-muted">{branch.branchCode} · {branch.address || "No address provided"}</p></div><span className={`status-badge ${branch.status}`}>{branch.status}</span></div></div><div className="grid-stats branch-kpis">{[["Members", kpis.totalMembers, Users], ["Active members", kpis.activeMembers, Users], ["Staff", kpis.staff, UserSquare2], ["Revenue", money(kpis.revenue), IndianRupee], ["Payments", kpis.payments, CreditCard], ["Attendance", kpis.attendance, CalendarCheck], ["Active memberships", kpis.activeMemberships, CalendarCheck]].map(([name, value, Icon]: any) => <div className="stat-card analytics-kpi" key={name}><Icon size={19} /><div><h3>{name}</h3><p className="stat-value">{value}</p></div></div>)}</div><div className="branch-detail-grid"><section className="glass-panel analytics-panel"><h2>Members</h2><div className="table-container"><table className="data-table"><thead><tr><th>Name</th><th>Plan</th><th>Status</th><th>Expiry</th></tr></thead><tbody>{members.length ? members.map(m => <tr key={m._id}><td>{m.user?.name || "Unknown"}</td><td>{m.currentPlan?.name || "No plan"}</td><td><span className={`status-badge ${m.status}`}>{m.status}</span></td><td>{m.membershipExpiryDate ? new Date(m.membershipExpiryDate).toLocaleDateString() : "-"}</td></tr>) : <tr><td colSpan={4}>No members in this branch.</td></tr>}</tbody></table></div></section><section className="glass-panel analytics-panel"><h2>Staff</h2><div className="table-container"><table className="data-table"><thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody>{staff.length ? staff.map(s => <tr key={s._id}><td>{s.name}</td><td>{s.role}</td><td><span className={`status-badge ${s.status}`}>{s.status}</span></td></tr>) : <tr><td colSpan={3}>No staff in this branch.</td></tr>}</tbody></table></div></section><section className="glass-panel analytics-panel"><h2>Recent payments</h2><div className="table-container"><table className="data-table"><thead><tr><th>Invoice</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.length ? payments.map(p => <tr key={p._id}><td>{p.invoiceNumber}</td><td>{money(p.amount)}</td><td><span className={`status-badge ${p.status}`}>{p.status}</span></td></tr>) : <tr><td colSpan={3}>No payments found.</td></tr>}</tbody></table></div></section><section className="glass-panel analytics-panel"><h2>Membership plans</h2>{data.plans?.length ? data.plans.map((plan: any) => <div className="breakdown-row" key={plan._id || plan.name}><span>{plan.name || "No plan"}</span><strong>{plan.count}</strong></div>) : <p className="text-muted">No membership data.</p>}</section></div></div>;
}